import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { scriptAiAdminFirestore } from '../server/firebase-admin.js';
import { FirestoreAutomationStore } from '../server/automation-store.js';
import { upsertAutomatedScript, scriptLinkStatus } from '../server/script-automation.js';
import { commitWorkspace, readHistory } from '../server/revision-store.js';
import { restoreScript, revisionKey } from '../server/script-revisions.js';
import { productionScript } from './helpers/production-script.mjs';
const enabled=process.env.RUN_REVISION_EMULATOR==='1';
test('Firestore emulator: transactional API history, reopen, restore, stale write and failure rollback', {skip:!enabled},async()=>{
 assert.equal(process.env.FIRESTORE_EMULATOR_HOST,'127.0.0.1:8787');
 assert.equal(process.env.FIREBASE_PROJECT_ID,'demo-script-revisions');
 const db=scriptAiAdminFirestore(),store=new FirestoreAutomationStore(),owner=`revision-test-${randomUUID()}`;
 const ref=db.collection('users').doc(owner);
 await ref.set({projects:[],scripts:[{id:'unrelated',name:'Preserve',blocks:[]}],privateUnrelated:{value:'keep'},createdAt:new Date('2026-01-01')});
 const input={script:productionScript({name:'NON-PUBLIC TEST v1'}),contentId:'disposable-content'};
 const v1=await store.updateWorkspace(owner,w=>upsertAutomatedScript(w,input));
 const scriptId=v1.result.scriptId;
 const contentFixture={id:'disposable-content',scriptConnection:{scriptId}};
 assert.equal(scriptLinkStatus(v1.workspace,contentFixture.scriptConnection.scriptId,contentFixture.id).matches,true);
 const v2=await store.updateWorkspace(owner,w=>upsertAutomatedScript(w,{...input,expectedRecordVersion:1,script:productionScript({name:'NON-PUBLIC TEST v2'})}));
 assert.equal(v2.result.recordVersion,2);
 // Reopen through a new store, rather than using the transition's returned object.
 const reopened=await new FirestoreAutomationStore().getWorkspace(owner);
 assert.equal(reopened.scripts.find(s=>s.id===scriptId).name,'NON-PUBLIC TEST v2');
 assert.deepEqual(reopened.reportSummary,{version:1,projects:reopened.projects.length,scripts:reopened.scripts.length});
 const projected=await ref.get();
 assert.equal(reopened.reportUpdatedAt.toMillis() <= projected.updateTime.toMillis(),true);
 assert.equal(projected.updateTime.toMillis()-reopened.reportUpdatedAt.toMillis() <= 1000,true,'Automation reporting timestamp must satisfy Dashboard freshness checks');
 const history=await readHistory(db,owner,scriptId);assert.deepEqual(history.revisions.map(r=>r.version),[2,1]);
 const options={operationId:'restore-v1',requestHash:'same-request'};
 const restore=()=>commitWorkspace(db,owner,async(w,get)=>({workspace:restoreScript(w,await get(scriptId,1),2),result:{id:scriptId}}),options);
 await restore();await restore();
 const current=await store.getWorkspace(owner);assert.equal(current.scripts.find(s=>s.id===scriptId).recordVersion,3);
 assert.deepEqual(current.reportSummary,{version:1,projects:current.projects.length,scripts:current.scripts.length});
 assert.equal(current.scripts.find(s=>s.id===scriptId).name,'NON-PUBLIC TEST v1');
 assert.equal(scriptLinkStatus(current,scriptId,contentFixture.id).matches,true);
 assert.equal(contentFixture.scriptConnection.scriptId,scriptId);
 assert.deepEqual(current.scripts.find(s=>s.id==='unrelated'),{id:'unrelated',name:'Preserve',blocks:[]});
 assert.deepEqual(current.privateUnrelated,{value:'keep'});assert.equal(current.createdAt.toDate().toISOString(),'2026-01-01T00:00:00.000Z');
 await assert.rejects(()=>store.updateWorkspace(owner,w=>upsertAutomatedScript(w,{...input,expectedRecordVersion:2,script:productionScript({name:'Stale'})})),e=>['REVISION_CONFLICT','MANUAL_EDIT_CONFLICT'].includes(e.code));
 await assert.rejects(()=>commitWorkspace(db,owner,async(w,get)=>({workspace:restoreScript(w,await get(scriptId,2),2)})),e=>e.code==='REVISION_CONFLICT');
 const before=(await ref.get()).data();
 await assert.rejects(()=>commitWorkspace(db,owner,w=>({workspace:{...w,scripts:w.scripts.map(s=>s.id===scriptId?{...s,name:'MUST NOT SAVE',invalid:()=>{}}:s)}})));
 assert.deepEqual((await ref.get()).data(),before);
 // A real commit-time create precondition failure must roll back the current body too.
 const collision=ref.collection('scriptRevisions').doc(revisionKey(scriptId,4));
 await collision.create({scriptId,version:4,script:{id:scriptId,name:'collision fixture'}});
 await assert.rejects(()=>commitWorkspace(db,owner,w=>({workspace:{...w,scripts:w.scripts.map(s=>s.id===scriptId?{...s,name:'Commit must fail'}:s)}})));
 assert.deepEqual((await ref.get()).data(),before);
 await collision.delete();
 assert.deepEqual((await readHistory(db,owner,scriptId)).revisions.map(r=>r.version),[3,2,1]);
 await db.recursiveDelete(ref);await db.terminate();
});
